trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa.pub'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'azure-resource-manager-service-connection'
    backendAzureRmResourceGroupName: 'terraform-be-rg'
    backendAzureRmStorageAccountName: 'storageaccountkrsharathrao79'
    backendAzureRmContainerName: 'storageaccountkrsharathrao79container'
    backendAzureRmKey: 'k8s-dev.tfstate'